# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd27c662b8b139702216cbf5aaf3f39fa8e1a4589492421f95dbcfc7f9aa86533502f5f61de64c6b9c336551e578bc36f431deb2767eed4db833195d10000146

test:
  secret_key_base: 8f53a821bd4aba6f23c844314a7b49e52b5465d8d236c934171f1b294b0ef9b4829ca89913eea36bccc088741bec6959456f7df4c747ed634edb7922f152f4c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
